import { Button, VerticalBox } from "std-widgets.slint";

component key inherits Rectangle {
    width: 50px;
    height: 50px;
    background: #020420;
    border-radius: 5px;
    border-color: #00DC82;
    border-width: 2px;
    Button {
        text: "W";
    }
}


export component AppWindow inherits Window {
    background: #020420;
    width: 800px;
    height: 550px;
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        key {}
    }
}

