import { Button, VerticalBox } from "std-widgets.slint";

component key inherits Rectangle {
    width: 50px;
    height: 50px;
    background: #020420;
    border-radius: 50px;
    border-color: #00DC82;
    border-width: 2px;
    clip: true;
    Button {
        width: 50px;
        height: 50px;
        text: "W";
        clicked => {
        }
    }
}

component Keyboard inherits Rectangle {
    width: 400px;
    height: 280px;
    HorizontalLayout {
        key {}
        key {}
    }
}


export component AppWindow inherits Window {
    background: #020420;
    width: 800px;
    height: 550px;
    in-out property <int> counter: 42;
    callback request-increase-value();
    
    Keyboard {}
    
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        key {}
    }
}

